### PR TITLE
[FEATURE] Find jobs in the subpages

### PR DESCRIPTION
**Pull request by AstritA**
Added ability to select jobs from child pages recursively

### CODE REVIEW

**Comment by nhovratov** [comment]
Hey, thank you for you pull-request! Can you explain to me, what specific problem this feature solves?

**Comment by AstritA** [comment]
Hello,
In my TYPO3 I have my jobs distributed in multiple sub-folder of a main folder.

With this feature, I only have to select the main folder and set the max subfolder level. The system I implemented is the same as the news extension.

I don't found recursive function who resolve my problem.

**Comment by nhovratov** [comment]
Ah, I see, thanks. I will test it.

**Comment by AstritA** [comment]
Perfect, thank you !

**Pull request closed without merging**
