### PR TITLE
Doc cleanup

### PR DESCRIPTION
**Pull request by ineswillenbrock**
I cleaned the languages in the code markup in FAQ/Index.rst to meet the guidelines.
Should I add the captions with the filenames, too?

### CODE REVIEW

**Comment by nhovratov** [comment]
Ah, cool thank you!

> Should I add the captions with the filenames, too?

That would be the cherry on the cake. Do it, if you want :)

**Comment by ineswillenbrock** [comment]
wait... sth went wrong with the markup

**Comment by ineswillenbrock** [comment]
no captions - but also no typos.
I'd have to investigate other extensions if its github or me...

**Comment by ineswillenbrock** [comment]
We've got a slight problem with the captions: I can add them but we'll loose the corresponding code blocks on github.
I investigated some other extensions and those, that have every code block visible on github don't use captions.
Those that do use them loose the visibility of these code blocks on github when previewing the documentation.
On the one hand it might be great to have the captions in the official docs, on the other hand there might be those, that try to use the docs on github.
Any preferences?

**Comment by nhovratov** [comment]
Stick with the captions. The official documentation is rendered on docs.typo3.org and all links are targeting that resource. If something doesn't work on GitHub it doesn't matter much.

**Comment by ineswillenbrock** [comment]
Please have a look if that's good.

**Review by nhovratov — APPROVED** [review]

**Comment by nhovratov** [comment]
Thank you very much!

**Pull request merged**
